{
 "title": "Dashboard_Ounas_Davy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temps total CPU système/utilisateur",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_system_seconds_total",
     "legendFormat": "{{name=\"est\"}}"
    },
    { "expr": "process_cpu_user_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre de requêtes HTTP total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 0 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nombre total de handles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 12 },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Somme des durées des requêtes HTTP (en s)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (http_request_duration_seconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}