apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
spec:
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-server
        image: ounas27/nodejs:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "200m"
        env:
        - name: REDIS_URL
          value: redis://redis-main.default.svc.cluster.local:6379
        - name: REDIS_REPLICAS_URL
          value: redis://redis-main.default.svc.cluster.local:6379
---      
apiVersion: v1
kind: Service
metadata:
  name: node-server-loadbalancer
spec:
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

